# Generated by Django 4.2.2 on 2023-06-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('roll', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
            ],
        ),
    ]
